root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/processor ./cmd/processor"
bin = "./tmp/processor"
log = "build.log"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true

[misc]
clean_on_exit = true

